CREATE TABLE COMPANIES(
	company_name VARCHAR PRIMARY KEY,
	created_on TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX COMPANIES_PRIMARY_INDEX ON COMPANIES (company_name);

INSERT INTO COMPANIES(company_name) VALUES('cisco');
INSERT INTO COMPANIES(company_name) VALUES('amdocs');