CREATE TABLE COMPANIES(
	company_name VARCHAR PRIMARY KEY,
    total_employees BIGINT NOT NULL DEFAULT 1,
	created_on TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX COMPANIES_PRIMARY_INDEX ON COMPANIES (company_name);

INSERT INTO COMPANIES(company_name) VALUES('CISCO');
INSERT INTO COMPANIES(company_name) VALUES('AMDOCS');